### PR TITLE
adding ModalForm and Buttons command and other things....

### PR DESCRIPTION
**Pull request by aminozomty**

### CODE REVIEW

**Comment by aminozomty** [comment]
i've added some cool stuff. you can change them. sorry i didn't have the enough time to test everything but you can check the code and see all the changes

**Comment by Kygekraqmak** [comment]
First, for what ModalForm is used?
Second, there are 4 lints in your pull requests. Please fix them.

**Comment by aminozomty** [comment]
can you contact me on discord aminozomty#5007
and i will explain everything

**Comment by Kygekraqmak** [comment]
> can you contact me on discord aminozomty#5007
> and i will explain everything
> and bc i didn't have time to explain bc i had some problems...
> Sorry

I've sent you a friend request. My Discord username is Kygekraqmak#6415.

**Pull request closed without merging**
